### ISSUE TITLE
PG can walk while jumping against a wall

### ISSUE THREAD

**Issue by MejoXP** [jacogasp/metro-jam#23]
**Describe the bug**
PG can walk while jumping against a wall

**To Reproduce**
1. Walk close to a wall
2. Jump
3. Keep walking arrow pressed
4. see how pg continues walking while in JumpIn

**Expected behavior**
JumpIn/Out against the wall

**Screenshots**
see video -> https://github.com/jacogasp/metro-jam/assets/101936400/5784946f-c16f-44b2-8246-6c3bd30c1382

**Comment by jacogasp** [comment]
It should be fixed
