### ISSUE TITLE
Jump animation does not end on Idle animation

### ISSUE THREAD

**Issue by MejoXP** [jacogasp/metro-jam#3]
**Describe the bug**
When you jump and await to land, the PG still run "jumpOut animation". To get back to Idle animation its necessary to jump again.

**To Reproduce**
1. press Jump (same behavior for all of the button keys) - holding or clicking the button has the same behavior
2. wait to land
3. see what the PG does....

**Expected behavior**
Jump - wait for landing [no button pressed in the meantime]

**Screenshots**
It's crystal clear

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: dell xps13 - 2018
 - OS: win10

**Comment by jacogasp** [comment]
Fixed by https://github.com/jacogasp/metro-jam/commit/1c71b11e8d70acb0ae28ff0e6bd4b6945652c592
