### ISSUE TITLE
NPG got stucked in tunnels playgrounds by overflipping

### ISSUE THREAD

**Issue by MejoXP** [jacogasp/metro-jam#4]
**Describe the bug**
A clear and concise description of what the bug is. -> it seems to be colliding on the top of the squared area

**To Reproduce**
Follow the NPG until it happens

**Expected behavior**
It should jump -> collide (side collision) -> flip

**Screenshots**
see video -> https://github.com/jacogasp/metro-jam/assets/101936400/9986c5fe-2b1f-4200-b71c-534532684b3e

**Comment by jacogasp** [comment]
Lol
