### ISSUE TITLE
PG got stucked instead of landing properly after slide+freefall

### ISSUE THREAD

**Issue by MejoXP** [jacogasp/metro-jam#6]
**Describe the bug**
While sliding out from a block line, animation jumpout starts but doesnt end properly: the PG get stuck in the first corner/wall encoutered.

**To Reproduce**
1. Go to a border
2. slide out from the block line, be sure to have space enough to free fall
3. see what happen

**Expected behavior**
1. slide out from a border
2. jumpout
3. landig

**Screenshots**
see video -> https://github.com/jacogasp/metro-jam/assets/101936400/e6141057-a847-4d39-92cf-3102871899b1

**Comment by jacogasp** [comment]
Dobbiamo tenerci tutte le registrazioni di questi bug per poi fare un video behind the scenes di tutti bloopers

**Comment by jacogasp** [comment]
Fixed in https://github.com/jacogasp/metro-jam/pull/8
