### ISSUE TITLE
PG got blocked while running+jumping when against a wall

### ISSUE THREAD

**Issue by MejoXP** [jacogasp/metro-jam#7]
**Describe the bug**
Running into a wall while pressing jump result in an half jump of the PG then land

**To Reproduce**
1. Run toawrds a wall and hold "run" button
2. Jump (hold run)
3. see error

**Expected behavior**
Running towards a wall like a clown, press jump and it jumps up at its maximum (plus the effect of the direction, in case)

**Screenshots**
see video -> https://github.com/jacogasp/metro-jam/assets/101936400/fa73792a-a875-497a-8edd-a0c0cfd9d9ee

**Comment by jacogasp** [comment]
Con l'ultima versione che fixa l'issue https://github.com/jacogasp/metro-jam/issues/3  tramite il commit https://github.com/jacogasp/metro-jam/commit/1c71b11e8d70acb0ae28ff0e6bd4b6945652c592 non riesco a riprodurre il bug. Puoi verificare per favore?

**Comment by jacogasp** [comment]
Bump

**Comment by jacogasp** [comment]
Chiudo perché non riesco a riprodurlo e probabilmente già fissato, vedi sopra.
Se necessario riaprilo @MejoXP
